server:
  port: 9020

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/ai-agent-station?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      username: ai-agent-station
      password: aiagent
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    pgvector:
      url: jdbc:postgresql://localhost:5432/aidb
      username: aidb
      password: admin
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
  ai:
    zhipuai:
      api-key: 0120679930954c13a2665e81b908b6aa.JH8jI1b0rcTcD5jx
      #      base-url: https://open.bigmodel.cn/api/paas/v4
      chat:
        options:
          model: glm-4.5-flash
      embedding:
        options:
          model: embedding-3
          dimensions: 1024


    vectorstore:
      pgvector:
        table-name: vector_store_ai_embedding
        initialize-schema: true
        dimensions: 1024


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
