version: '3.8'

#  docker pull swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/pgvector/pgvector:pg17-linuxarm64
#  docker tag  swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/pgvector/pgvector:pg17-linuxarm64  docker.io/pgvector/pgvector:pg17

services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: aidb          # 默认数据库名
      POSTGRES_USER: aidb      # 应用用户（非超级用户）
      POSTGRES_PASSWORD: admin  # 请务必修改！
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"                  # 映射到宿主机 5432
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      # 可选：挂载自定义初始化脚本
      # - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidb -d aidb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgvector_data:
