server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aidb
    username: aidb
    password: admin
    driver-class-name: org.postgresql.Driver
  ai:
    zhipuai:
      api-key: 0120679930954c13a2665e81b908b6aa.JH8jI1b0rcTcD5jx
      #      base-url: https://open.bigmodel.cn/api/paas/v4
      chat:
        options:
          model: glm-4.5-flash
    mcp:
      client:
        enabled: true
        stdio:
          servers-configuration: classpath:/config/mcp-servers.json
        sse:
          connections:
            sse1:
              url: http://localhost:9012



        name:  mcp-client
        request-timeout: 180000
#      远程server
#      server:
#        base-url:

