server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aidb
    username: aidb
    password: admin
    driver-class-name: org.postgresql.Driver
  ai:
    zhipuai:
      api-key: APIKEY
#      base-url: https://open.bigmodel.cn/api/paas/v4
      chat:
          options:
              model: glm-4.5-flash
      embedding:
        options:
          model: embedding-3
          dimensions: 1024


    vectorstore:
      pgvector:
        table-name: ai_vector
        initialize-schema: true
        dimensions: 1024


logging:
  level:
    org.springframework.web.client.RestClient: DEBUG